---
abstract: 'a simple way of doing messaging.'
author:
  - 'Tomas (t0m) Doran <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: lgpl_2_1
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing
name: Message-Passing
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::Handle::UDP: 0
  Config::Any: 0
  DateTime: 0
  IO::Handle: 0
  JSON: 2.0
  Module::Runtime: 0.013
  Moo: 0.091011
  MooX::Options: 3.71
  MooX::Types::MooseLike: 0.08
  Package::Variant: 1.001001
  String::RewritePrefix: 0
  Sys::Hostname::Long: 0
  Task::Weaken: 0
  Try::Tiny: 0
  namespace::clean: 0.23
  perl: 5.8.4
resources:
  license: http://opensource.org/licenses/lgpl-license.php
  repository: git://github.com/suretec/Message-Passing.git
version: 0.113
x_authority: cpan:GHENRY
